//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestChat.IRC.Data.Prefs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrefsRsrcs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrefsRsrcs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestChat.IRC.Data.Prefs.PrefsRsrcs", typeof(PrefsRsrcs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Chat has exited..
        /// </summary>
        internal static string strDefQuitMsg {
            get {
                return ResourceManager.GetString("strDefQuitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists custom command sets you can run as one..
        /// </summary>
        internal static string strGlobalAliasesDesc {
            get {
                return ResourceManager.GetString("strGlobalAliasesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        internal static string strGlobalAliasesTitle {
            get {
                return ResourceManager.GetString("strGlobalAliasesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any alternate nicks that Best Chat should use if your normal nick isn&apos;t available.  You don&apos;t need to include your default nick..
        /// </summary>
        internal static string strGlobalAltNicksDesc {
            get {
                return ResourceManager.GetString("strGlobalAltNicksDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterate Nicks.
        /// </summary>
        internal static string strGlobalAltNicksTitle {
            get {
                return ResourceManager.GetString("strGlobalAltNicksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups tasks that Best Chat runs at select events.  These are all commands you were otherwise enter from the input box and can include those from plugins and aliases..
        /// </summary>
        internal static string strGlobalAutoPerformDesc {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-perform.
        /// </summary>
        internal static string strGlobalAutoPerformTitle {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter commands to run when joining a channel on any network.  This might be overridden by the settings for each network and further by individual channels..
        /// </summary>
        internal static string strGlobalAutoPerformWhenJoiningChanDesc {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformWhenJoiningChanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When joining a channel on any network.
        /// </summary>
        internal static string strGlobalAutoPerformWhenJoiningChanTitle {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformWhenJoiningChanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any commands to run when you join any network.  Thise can include commands from plugins and aliases..
        /// </summary>
        internal static string strGlobalAutoPerformWhenJoiningNetDesc {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformWhenJoiningNetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When joining a network.
        /// </summary>
        internal static string strGlobalAutoPerformWhenJoiningNetTitle {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformWhenJoiningNetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter commands to run when opening a user chat on any network.  This might be overridden by the settings for each network..
        /// </summary>
        internal static string strGlobalAutoPerformWhenOpeningUserChatDesc {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformWhenOpeningUserChatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When opening a user chat on any network.
        /// </summary>
        internal static string strGlobalAutoPerformWhenOpeningUserChatTitle {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformWhenOpeningUserChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any commands to run when Best Chat starts.  This can include plugins and aliases..
        /// </summary>
        internal static string strGlobalAutoPerformWhenStartingBestChatDesc {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformWhenStartingBestChatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Starting Best Chat.
        /// </summary>
        internal static string strGlobalAutoPerformWhenStartingBestChatTitle {
            get {
                return ResourceManager.GetString("strGlobalAutoPerformWhenStartingBestChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your connection is lost unexpectedly, Best Chat can automatically reconnect to the server for you..
        /// </summary>
        internal static string strGlobalConnAutoReconnectDesc {
            get {
                return ResourceManager.GetString("strGlobalConnAutoReconnectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect when disconnected unexpectedly.
        /// </summary>
        internal static string strGlobalConnAutoReconnectTitle {
            get {
                return ResourceManager.GetString("strGlobalConnAutoReconnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For multiple clients to correctly read messages with non-ASCII characters on IRC, they need to use the same character encoding..
        /// </summary>
        internal static string strGlobalConnCharEncodingDesc {
            get {
                return ResourceManager.GetString("strGlobalConnCharEncodingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_haracter Encoding.
        /// </summary>
        internal static string strGlobalConnCharEncodingTitle {
            get {
                return ResourceManager.GetString("strGlobalConnCharEncodingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a default quit message to use when on is not explicitly specified for a network or via the /quit command..
        /// </summary>
        internal static string strGlobalConnDefQuitMsgDesc {
            get {
                return ResourceManager.GetString("strGlobalConnDefQuitMsgDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Quit _Message.
        /// </summary>
        internal static string strGlobalConnDefQuitMsgTitle {
            get {
                return ResourceManager.GetString("strGlobalConnDefQuitMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These preferences affect how Best Chat connects to the Internet..
        /// </summary>
        internal static string strGlobalConnDesc {
            get {
                return ResourceManager.GetString("strGlobalConnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows Best Chat to connect to servers that require an ident response.
        /// </summary>
        internal static string strGlobalConnEnableIdentDesc {
            get {
                return ResourceManager.GetString("strGlobalConnEnableIdentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable _Identification Server during connection process.
        /// </summary>
        internal static string strGlobalConnEnableIdentTitle {
            get {
                return ResourceManager.GetString("strGlobalConnEnableIdentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is number of times Best Chat attempts to connect to a server or network.  A value of 1 means Best Chat will never attempt to reconnect to the server..
        /// </summary>
        internal static string strGlobalConnMaxAttemptsDesc {
            get {
                return ResourceManager.GetString("strGlobalConnMaxAttemptsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Connection _Attempts:.
        /// </summary>
        internal static string strGlobalConnMaxAttemptsTitle {
            get {
                return ResourceManager.GetString("strGlobalConnMaxAttemptsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is turned on, Best Chat will try (only once) to rejoin a channel you got kicked from.  Note: Some channels dislike auto-rejoin and will ban you.  So be careful..
        /// </summary>
        internal static string strGlobalConnRejoinAfterKickDesc {
            get {
                return ResourceManager.GetString("strGlobalConnRejoinAfterKickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_ejoin when kicked.
        /// </summary>
        internal static string strGlobalConnRejoinAfterKickTitle {
            get {
                return ResourceManager.GetString("strGlobalConnRejoinAfterKickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connection.
        /// </summary>
        internal static string strGlobalConnTitle {
            get {
                return ResourceManager.GetString("strGlobalConnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, Best Chat will attempt to reconnect to any server forever.  If unchecked, the limit will be to the right..
        /// </summary>
        internal static string strGlobalConnUnlimitedAttemptsDesc {
            get {
                return ResourceManager.GetString("strGlobalConnUnlimitedAttemptsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited Attempts?.
        /// </summary>
        internal static string strGlobalConnUnlimitedAttemptsTitle {
            get {
                return ResourceManager.GetString("strGlobalConnUnlimitedAttemptsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCC lets you bypass a server once you connected in order to talk to a specific user, send them files, or receive files from them.  Use this tab to control those settings..
        /// </summary>
        internal static string strGlobalDccDesc {
            get {
                return ResourceManager.GetString("strGlobalDccDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies where to save all files received via DCC.
        /// </summary>
        internal static string strGlobalDccDownloadsFolderDesc {
            get {
                return ResourceManager.GetString("strGlobalDccDownloadsFolderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads Folder.
        /// </summary>
        internal static string strGlobalDccDownloadsFolderTitle {
            get {
                return ResourceManager.GetString("strGlobalDccDownloadsFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must check this to allow Best Chat to use DCC.  Otherwise, all DCC chats will be blocked and DCC won&apos;t appear in the menus..
        /// </summary>
        internal static string strGlobalDccEnabledDesc {
            get {
                return ResourceManager.GetString("strGlobalDccEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string strGlobalDccEnabledTitle {
            get {
                return ResourceManager.GetString("strGlobalDccEnabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, Best Chat will ask the server for the IP address to use..
        /// </summary>
        internal static string strGlobalDccGetIpFromServerDesc {
            get {
                return ResourceManager.GetString("strGlobalDccGetIpFromServerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the local IP from the server.
        /// </summary>
        internal static string strGlobalDccGetIpFromServerTitle {
            get {
                return ResourceManager.GetString("strGlobalDccGetIpFromServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCC (Direct Client Chat).
        /// </summary>
        internal static string strGlobalDccTitle {
            get {
                return ResourceManager.GetString("strGlobalDccTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string strGlobalDesc {
            get {
                return ResourceManager.GetString("strGlobalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any strings you want to trigger a notify besides your nick.  This could be anything you&apos;re interested in, &quot;@op&quot;, &quot;@room&quot;, etc.  Your nick is implied.  If you turned on Agressive Notify in the application&apos;s main preferences, Best Chat will try to get your attention.
        /// </summary>
        internal static string strGlobalStalkWordsDesc {
            get {
                return ResourceManager.GetString("strGlobalStalkWordsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stalk Words.
        /// </summary>
        internal static string strGlobalStalkWordsTitle {
            get {
                return ResourceManager.GetString("strGlobalStalkWordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string strGlobalTitle {
            get {
                return ResourceManager.GetString("strGlobalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All IRC specific settings are here..
        /// </summary>
        internal static string strIrcRootDesc {
            get {
                return ResourceManager.GetString("strIrcRootDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC.
        /// </summary>
        internal static string strIRCRootTitle {
            get {
                return ResourceManager.GetString("strIRCRootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists preferences specific to the network {0}.
        /// </summary>
        internal static string strNetDesc {
            get {
                return ResourceManager.GetString("strNetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} network preferences.
        /// </summary>
        internal static string strNetTitle {
            get {
                return ResourceManager.GetString("strNetTitle", resourceCulture);
            }
        }
    }
}
