//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestChat.GUI.Ctrls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestChat.GUI.Ctrls.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string strFontWeightBold {
            get {
                return ResourceManager.GetString("strFontWeightBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demi-Bold/Semi-Bold.
        /// </summary>
        internal static string strFontWeightDemiBold {
            get {
                return ResourceManager.GetString("strFontWeightDemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra-Black/Ultra-Black.
        /// </summary>
        internal static string strFontWeightExtraBlack {
            get {
                return ResourceManager.GetString("strFontWeightExtraBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra-Bold/Ultra-Bold.
        /// </summary>
        internal static string strFontWeightExtraBold {
            get {
                return ResourceManager.GetString("strFontWeightExtraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Light/Ultra Light.
        /// </summary>
        internal static string strFontWeightExtraLight {
            get {
                return ResourceManager.GetString("strFontWeightExtraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black/Heavy.
        /// </summary>
        internal static string strFontWeightHeavy {
            get {
                return ResourceManager.GetString("strFontWeightHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string strFontWeightLight {
            get {
                return ResourceManager.GetString("strFontWeightLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string strFontWeightMedium {
            get {
                return ResourceManager.GetString("strFontWeightMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal/Regular.
        /// </summary>
        internal static string strFontWeightNormal {
            get {
                return ResourceManager.GetString("strFontWeightNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin.
        /// </summary>
        internal static string strFontWeightThin {
            get {
                return ResourceManager.GetString("strFontWeightThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show extended help for this preference.  Click again to hide that help..
        /// </summary>
        internal static string strShowHelpButtonToolTipText {
            get {
                return ResourceManager.GetString("strShowHelpButtonToolTipText", resourceCulture);
            }
        }
    }
}
