//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestChat.IRC.ProtocolMgr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rsrcs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rsrcs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestChat.IRC.ProtocolMgr.Rsrcs", typeof(Rsrcs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _BNC Manager.
        /// </summary>
        internal static string strFileBncMgrMenuItemTitle {
            get {
                return ResourceManager.GetString("strFileBncMgrMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the BNC Manager.  From here, you can customize how Best Chat handles bouncers..
        /// </summary>
        internal static string strFileBncMgrMenuItemToolTip {
            get {
                return ResourceManager.GetString("strFileBncMgrMenuItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_RC.
        /// </summary>
        internal static string strFileMenuItemTitle {
            get {
                return ResourceManager.GetString("strFileMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holds all menu items for the IRC system in Best Chat.
        /// </summary>
        internal static string strFileMenuItemToolTip {
            get {
                return ResourceManager.GetString("strFileMenuItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Network Manager.
        /// </summary>
        internal static string strFileNetworkMgrMenuItemTitle {
            get {
                return ResourceManager.GetString("strFileNetworkMgrMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Network Manager.  From here, you can add, remove, or customize IRC networks available through out the rest of Best Chat..
        /// </summary>
        internal static string strFileNetworkMgrMenuItemToolTip {
            get {
                return ResourceManager.GetString("strFileNetworkMgrMenuItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implements the Internet Relay Chat protocol for Best Chat.  Without this module, Best Chat doesn&apos;t support IRC..
        /// </summary>
        internal static string strTranslatedProtDesc {
            get {
                return ResourceManager.GetString("strTranslatedProtDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Relay Chat (IRC).
        /// </summary>
        internal static string strTranslatedProtName {
            get {
                return ResourceManager.GetString("strTranslatedProtName", resourceCulture);
            }
        }
    }
}
